### ISSUE TITLE
optionally use a custom command to gracefully close specific windows

### ISSUE THREAD

**Issue by sharethewisdom** [vilnius-leopold/close-all-windows#1]
(original title: optional xdotool dependency feature)
I thought maybe you'd want some sort of routine to gracefully close windows that usually save sessions etc when closed manually, i.e. `send_keys_and_wait`. 

A config like `~/.close-all-windows` could call a `for_window` function [similar to i3wm config](http://i3wm.org/docs/userguide.html#_arbitrary_commands_for_specific_windows_for_window). In order to automatically send keys to the specified windows (using XTest or XSendEvent), the close_threads would first set a flag for windows when local_win[:p_name] and local_win[:title] matches, and call `send_keys_and_wait()` which uses, for example, `xdotool search` and then `wait_for_process_to_close(win[:pid])`. If PID of the the target application that we're intending to close still exists we should try closing it gracefully using the normal routine.

For instance, I intend to close my Firefox+Vimperator gracefully, saving the browsing session.
-  The keys in the config:
  
  `for_window [class="(?i)firefox" title="\(Vimperator\)$"] key Tab Escape Z Z`
-  should ultimately be send to the first matching window
  
  `xdotool search --limit 1 --name Vimperator key Tab Escape Z Z`
-  Similary, I'd want the virtualbox to Power off:
  
  `for_window [class="(?i)vboxsdl"] key Control_R+q`

**Comment by vilnius-leopold** [comment]
thanks for your thoughts. I'll look into it. Maybe I'll bake it into the script or expose some hooks where you can run arbitrary scripts when a certain window closes.

**Comment by vilnius-leopold** [comment]
I'm currently working on the feature on the development branch. I created a sample conf file of how it could work and implemented a working parser. I still have to tie it in to work with the script though.
https://github.com/vilnius-leopold/close-all-windows/blob/development/close-all-windows.conf
I guess the feature should be available with the next release.

**Comment by sharethewisdom** [comment]
I'm glad to see you work on it!
Another more foolproof thing to do would be to invoke a menu item from the menu bar of the specified window. [This is what](http://www.autohotkey.com/docs/commands/WinMenuSelectItem.htm) I used on Windows. But I'm not familiar with the gnome, kde or whatever X shell and I'm not aware of any tool that has the same effect. Sorry to just throw in yet another thought.

**Comment by vilnius-leopold** [comment]
Every idea can make the script better and I don't have to implement everything if I don't want to.
About the menu. Not sure if all wms implement it or if it depends on the application, but I think just tabbing the `Alt` key toggles the menu and e.g. `Alt+F` toggles the File tab in the menu... so that might work via `xdotool`. One way or the other I think, because you can run any arbitrary command on a window (as long as you have the pid or window id) from within your config, you can use any tool to execute a command. The config would kinda provide a "plugin" structure.
I think the main purpose of the script will be to 
1) find open windows, 
2) extract as much meta data about this window as possible to act upon (exposed via environment variables)
3) execute a close command - via config "plugin"
4) wait for them to close. 
So I guess as long as there is a tool to accommodate what you're trying to do, it will work.

**Comment by sharethewisdom** [comment]
Any method that involves programs to talk to each other is preferable to sending keys. So by foolproof I meant: sending a message to the window or a control (like the message that would be send if the menu item "Shutdown" is clicked). A few problems with a set of keystrokes are matters of localisation and timing, and windows may have to be visible and/or active in order to receive them. The Autohotkey command [PostMessage](http://www.autohotkey.com/docs/commands/PostMessage.htm) does exactly that on Windows, and it returns an error flag if the window or control does not exist. 

>  as long as there is a tool to accommodate what you're trying to do, it will work

Great. But error/log handling could be useful in your script. We don't need to wait for it to close if a _close command_ returns such an error flag, for instance.

**Comment by vilnius-leopold** [comment]
I totally agree. Sending keys isn't fool proof and polling for close events is inefficient, but I don't know any other methods. Maybe digging deeper into X11, WM specific or application specific APIs - but I know very little about those apis. I believe if there was a better way of controling windows/menus `wmctrl` or `xdotool` would have implemented it. Let me know if you come across a better way, I didn't find anything so far.

**Comment by vilnius-leopold** [comment]
I moved this issue over to https://github.com/vilnius-leopold/close-all-windows/issues/2

**Comment by vilnius-leopold** [comment]
The **v0.0.3** release with the config file feature is ready for testing on the [development branch](https://github.com/vilnius-leopold/close-all-windows/tree/development). If anyone cares to test this release before I merge it into master please go ahead. If you run ArchLinux you can simply create a package by running `make archlinux-package`. The resulting package will reside in `build/`.
